id: P000624
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG3397
  title: འདུལ་བ་མདོའི་དགོངས་པ་གསལ་བར་བྱེད་པ།
  author: ''
  volumes:
    67b4df8bc5a64e60855f632fbaacbfd0:
      image_group_id: I1KG3475
      title: ''
      volume_number: 1
      total_pages: 1040
    766f571a04ed4575bd02450f46f0b953:
      image_group_id: I1KG3476
      title: ''
      volume_number: 2
      total_pages: 940
