id: I3470BE6E
legacy_id: P000624
ocr_import_info:
  bdrc_scan_id: W1KG3397
  source: bdrc
  ocr_info:
    timestamp: '2020-03-28T09:58:30'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T15:00:06.287210+00:00'
last_modified: 2022-08-31 23:00:47.104002
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG3397
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG3397
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: འདུལ་བ་མདོའི་དགོངས་པ་གསལ་བར་བྱེད་པ།
  author: དགེ་འདུན་གྲུབ་པ།
statistics:
  ocr_word_mean_confidence_index: 0.915101354394742
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I1KG3475:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG3475
      total_pages: 1040
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG3475.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9156171897897161
    legacy_id: v001
  I1KG3476:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG3476
      total_pages: 940
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1KG3476.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9145045736519386
    legacy_id: v002
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
