id: I3470BE6E
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T10:04:41+00:00'
last_modified: '2022-06-07T12:29:26.838907+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG3397
  title: འདུལ་བ་མདོའི་དགོངས་པ་གསལ་བར་བྱེད་པ།
  author: ''
  base:
    CF65:
      image_group_id: I1KG3475
      title: ''
      total_pages: 1040
      order: 1
      base_file: CF65.txt
    C0EE:
      image_group_id: I1KG3476
      title: ''
      total_pages: 940
      order: 2
      base_file: C0EE.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
